### ISSUE TITLE
Bug: AppCrash by  text input for the strings "settings_confidence_text, settings_postpone_text, settings_low_glucose_text, settings_high_glucose_text"

### ISSUE THREAD

**Issue by Matze1985** [pimpimmi/LibreAlarm#10]
AppCrash by text input for the strings "settings_confidence_text, settings_postpone_text, settings_low_glucose_text, settings_high_glucose_text"

Better is a input only in number format.

**Comment by pimpimmi** [comment]
Thanks, I'll look into it

**Comment by Matze1985** [comment]
The same problem by the screen:
Not connected
button_wait: WAIT (Possibly make the button invisible)

**Comment by pimpimmi** [comment]
Done
