### ISSUE TITLE
Enhancement Question: Up/Down Glucose Value Control

### ISSUE THREAD

**Issue by Matze1985** [pimpimmi/LibreAlarm#11]
I use Libre alarm all day.
Here my idea, when in string "settings_postpone_text" for example 10 minutes stands than a option for Glucose Value Up/Down in this time (1.0 or 2.0) up/down mmol/l control to add.
One always knows, when a value rises or falls too fast.

Is the idea good?

**Comment by pimpimmi** [comment]
I don't quite get it. You mean we should have an option to still get an alarm if glucose value rises/falls fast?

**Comment by Matze1985** [comment]
Yes, is a idea, but for people with sporting activities of benefit.

With options:
- Time (example numberfield: 20 min.)
- Glucose value rises/falls for alarm in this time (example numberfield: 2 mmol/l)

What do you think?

BR

**Comment by Matze1985** [comment]
A alarm function is in nightscout integrated,

Alarms options:
    Urgent High Alarm
    High Alarm
    Low Alarm
    Urgent Low Alarm

BR Mathias
