### ISSUE TITLE
Other smart watches

### ISSUE THREAD

**Issue by ramjar** [pimpimmi/LibreAlarm#16]
Hi,

Wonderful project you guys are working on. 

Is it possible to buy random cheap smart watch from aliexpress and make it work with the librealarm? (As long as it's android and NFC support)?

Example of a watch 
https://m.aliexpress.com/item/32648113464.html

Thanks

**Comment by pimpimmi** [comment]
Hi rajmar,

Everything is possible. It won't work with this project though.

Best regards,
Joachim
