### ISSUE TITLE
Sony swr50

### ISSUE THREAD

**Issue by lassondes43** [pimpimmi/LibreAlarm#41]
Why root sony swr50 to be a collector when the Nightrider emits bluetooth ... so why activate the nfc if you only want to play bluetooth!

**Comment by pimpimmi** [comment]
Not sure I follow. If you want to read the sensor using a Smartwatch you need to enable NFC. The sensor uses NFC, not Bluetooth.

**Comment by lassondes43** [comment]
The emet sensor in NFC and the nigthrider retransmits in bluetooth, that's it!

**Comment by lassondes43** [comment]
I am badly explain. I have the watch sony swr50 can read the data alone without a phone but only in bluetooth and not as the abboot player in nfc. Or must the watch be rooter!

**Comment by lassondes43** [comment]
Comment fermer ce post
