### ISSUE TITLE
I get on error on watch  "unfortunately librealarm has stopped"

### ISSUE THREAD

**Issue by isuran** [pimpimmi/LibreAlarm#5]
05-27 23:53:00.996 21340-21340/com.pimpimmobile.librealarm I/ActivityManager: Timeline: Activity_idle id: android.os.BinderProxy@42b2a980 time:20654842
05-27 23:53:00.996 21340-21340/com.pimpimmobile.librealarm I/GLUCOSE::WearService: Wear connected
05-27 23:53:01.006 21340-21385/com.pimpimmobile.librealarm I/GLUCOSE::WearableApi: sending to 1665e0a3, command: /update
05-27 23:53:02.026 21340-21340/com.pimpimmobile.librealarm I/GLUCOSE::WearService: Message receiver: /status_update, 2:1:5:1464385592286
05-27 23:53:08.766 21340-21340/com.pimpimmobile.librealarm I/ViewRootImpl: ViewRoot's Touch Event : Touch Down
05-27 23:53:08.836 21340-21340/com.pimpimmobile.librealarm I/ViewRootImpl: ViewRoot's Touch Event : Touch UP
05-27 23:53:08.866 21340-21536/com.pimpimmobile.librealarm I/GLUCOSE::WearableApi: sending to 1665e0a3, command: /trigger_glucose
05-27 23:53:09.546 21340-21340/com.pimpimmobile.librealarm I/ViewRootImpl: ViewRoot's Touch Event : Touch Down
05-27 23:53:09.596 21340-21340/com.pimpimmobile.librealarm I/ViewRootImpl: ViewRoot's Touch Event : Touch UP
05-27 23:53:09.616 21340-21549/com.pimpimmobile.librealarm I/GLUCOSE::WearableApi: sending to 1665e0a3, command: /trigger_glucose
05-27 23:53:11.776 21340-21340/com.pimpimmobile.librealarm I/ViewRootImpl: ViewRoot's Touch Event : Touch Down
05-27 23:53:12.036 21340-21340/com.pimpimmobile.librealarm I/ViewRootImpl: ViewRoot's Touch Event : Touch UP
05-27 23:53:12.666 21340-21340/com.pimpimmobile.librealarm I/ViewRootImpl: ViewRoot's Touch Event : Touch Down
05-27 23:53:13.006 21340-21340/com.pimpimmobile.librealarm I/ViewRootImpl: ViewRoot's Touch Event : Touch UP
05-27 23:53:13.546 21340-21340/com.pimpimmobile.librealarm I/ViewRootImpl: ViewRoot's Touch Event : Touch Down
05-27 23:53:13.886 21340-21340/com.pimpimmobile.librealarm I/ViewRootImpl: ViewRoot's Touch Event : Touch UP
05-27 23:53:14.196 21340-21340/com.pimpimmobile.librealarm D/cliptray_Editor:  setInputTypeforClipTray(): 0
05-27 23:53:15.256 21340-21340/com.pimpimmobile.librealarm I/ViewRootImpl: ViewRoot's Touch Event : Touch Down
05-27 23:53:15.406 21340-21340/com.pimpimmobile.librealarm I/ViewRootImpl: ViewRoot's Touch Event : Touch UP
05-27 23:53:15.886 21340-21340/com.pimpimmobile.librealarm D/BubblePopupHelper: isShowingBubblePopup : false
05-27 23:53:15.886 21340-21340/com.pimpimmobile.librealarm D/BubblePopupHelper: isShowingBubblePopup : false
05-27 23:53:15.886 21340-21340/com.pimpimmobile.librealarm D/BubblePopupHelper: isShowingBubblePopup : false
05-27 23:53:15.886 21340-21340/com.pimpimmobile.librealarm D/BubblePopupHelper: isShowingBubblePopup : false
05-27 23:53:15.936 21340-21340/com.pimpimmobile.librealarm I/GLUCOSE::WearableApi: send data, message: /settings, PostponeSettings:120000:true,HighGlucoseSettings:10.0:true,LowGlucoseSettings:3.5:true,ConfidenceSettings:1.0:true,
05-27 23:53:15.936 21340-21340/com.pimpimmobile.librealarm I/GLUCOSE::WearableApi: send data, message: /settings
05-27 23:53:16.016 21340-21340/com.pimpimmobile.librealarm D/BubblePopupHelper: isShowingBubblePopup : false
05-27 23:53:16.016 21340-21340/com.pimpimmobile.librealarm D/BubblePopupHelper: isShowingBubblePopup : false
05-27 23:53:16.016 21340-21340/com.pimpimmobile.librealarm D/BubblePopupHelper: isShowingBubblePopup : false
05-27 23:53:16.016 21340-21340/com.pimpimmobile.librealarm D/BubblePopupHelper: isShowingBubblePopup : false
05-27 23:53:16.016 21340-21340/com.pimpimmobile.librealarm D/BubblePopupHelper: isShowingBubblePopup : false
05-27 23:53:16.016 21340-21340/com.pimpimmobile.librealarm D/BubblePopupHelper: isShowingBubblePopup : false
05-27 23:53:16.016 21340-21340/com.pimpimmobile.librealarm D/BubblePopupHelper: isShowingBubblePopup : false
05-27 23:53:16.026 21340-21340/com.pimpimmobile.librealarm D/BubblePopupHelper: isShowingBubblePopup : false
05-27 23:53:16.286 21340-21340/com.pimpimmobile.librealarm I/ViewRootImpl: ViewRoot's Touch Event : Touch Down
05-27 23:53:16.586 21340-21340/com.pimpimmobile.librealarm I/ViewRootImpl: ViewRoot's Touch Event : Touch UP
05-27 23:53:16.756 21340-21340/com.pimpimmobile.librealarm D/BubblePopupHelper: isShowingBubblePopup : false
05-27 23:53:16.756 21340-21340/com.pimpimmobile.librealarm D/BubblePopupHelper: isShowingBubblePopup : false
05-27 23:53:16.756 21340-21340/com.pimpimmobile.librealarm D/BubblePopupHelper: isShowingBubblePopup : false
05-27 23:53:16.756 21340-21340/com.pimpimmobile.librealarm D/BubblePopupHelper: isShowingBubblePopup : false
05-27 23:53:17.216 21340-21340/com.pimpimmobile.librealarm I/GLUCOSE::WearService: Message receiver: /settings, OK
05-27 23:53:17.246 21340-21340/com.pimpimmobile.librealarm I/GLUCOSE::WearService: Message receiver: /status_update, 2:1:5:1464386116821
05-27 23:53:19.716 21340-21340/com.pimpimmobile.librealarm I/ViewRootImpl: ViewRoot's Touch Event : Touch Down
05-27 23:53:19.826 21340-21340/com.pimpimmobile.librealarm I/ViewRootImpl: ViewRoot's Touch Event : Touch UP
05-27 23:53:22.116 21340-21340/com.pimpimmobile.librealarm I/ViewRootImpl: ViewRoot's Touch Event : Touch Down
05-27 23:53:22.156 21340-21340/com.pimpimmobile.librealarm I/ViewRootImpl: ViewRoot's Touch Event : Touch UP
05-27 23:53:22.176 21340-21776/com.pimpimmobile.librealarm I/GLUCOSE::WearableApi: sending to 1665e0a3, command: /trigger_glucose
05-27 23:53:27.406 21340-21340/com.pimpimmobile.librealarm I/ViewRootImpl: ViewRoot's Touch Event : Touch Down
05-27 23:53:27.466 21340-21861/com.pimpimmobile.librealarm I/GLUCOSE::WearableApi: sending to 1665e0a3, command: /trigger_glucose
05-27 23:53:27.466 21340-21340/com.pimpimmobile.librealarm I/ViewRootImpl: ViewRoot's Touch Event : Touch UP
05-27 23:53:28.046 21340-21340/com.pimpimmobile.librealarm I/ViewRootImpl: ViewRoot's Touch Event : Touch Down
05-27 23:53:28.106 21340-21340/com.pimpimmobile.librealarm I/ViewRootImpl: ViewRoot's Touch Event : Touch UP
05-27 23:53:28.146 21340-21877/com.pimpimmobile.librealarm I/GLUCOSE::WearableApi: sending to 1665e0a3, command: /trigger_glucose
05-27 23:53:32.076 21340-21340/com.pimpimmobile.librealarm I/ViewRootImpl: ViewRoot's Touch Event : Touch Down
05-27 23:53:32.146 21340-21340/com.pimpimmobile.librealarm I/ViewRootImpl: ViewRoot's Touch Event : Touch UP

E/AndroidRuntime( 7911): Process: com.pimpimmobile.librealarm, PID: 7911
E/AndroidRuntime( 7911): java.lang.NumberFormatException: Invalid long: "1.0"
E/AndroidRuntime( 7911):        at java.lang.Long.invalidLong(Long.java:124)
E/AndroidRuntime( 7911):        at java.lang.Long.parse(Long.java:361)
E/AndroidRuntime( 7911):        at java.lang.Long.parseLong(Long.java:352)
E/AndroidRuntime( 7911):        at java.lang.Long.parseLong(Long.java:318)
E/AndroidRuntime( 7911):        at java.lang.Long.valueOf(Long.java:476)
E/AndroidRuntime( 7911):        at com.pimpimmobile.librealarm.shareddata.settings.PostponeSettings.getExtraData(PostponeSettings.java:21)
E/AndroidRuntime( 7911):        at com.pimpimmobile.librealarm.shareddata.settings.SettingsUtils.createSettingsTransferString(SettingsUtils.java:51)
E/AndroidRuntime( 7911):        at com.pimpimmobile.librealarm.MainActivity$2.onDrawerClosed(MainActivity.java:84)
E/AndroidRuntime( 7911):        at android.support.v4.widget.DrawerLayout.dispatchOnDrawerClosed(DrawerLayout.java:839)
E/AndroidRuntime( 7911):        at android.support.v4.widget.DrawerLayout.updateDrawerState(DrawerLayout.java:809)
E/AndroidRuntime( 7911):        at android.support.v4.widget.DrawerLayout$ViewDragCallback.onViewDragStateChanged(DrawerLayout.java:2028)
E/AndroidRuntime( 7911):        at android.support.v4.widget.ViewDragHelper.setDragState(ViewDragHelper.java:875)
E/AndroidRuntime( 7911):        at android.support.v4.widget.ViewDragHelper$2.run(ViewDragHelper.java:336)
E/AndroidRuntime( 7911):        at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 7911):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 7911):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 7911):        at android.app.ActivityThread.main(ActivityThread.java:5105)
E/AndroidRuntime( 7911):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 7911):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 7911):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
E/AndroidRuntime( 7911):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
E/AndroidRuntime( 7911):        at dalvik.system.NativeStart.main(Native Method)

**Comment by pimpimmi** [comment]
Right, the transfer system between the watch is a bit stupid at the moment. It looks like you're trying to postpone the alarm by 1.0 minutes, it can't handle decimal numbers. For now, it should be fixed if you open the drawer and set "next check in" to a non-decimal number.

**Comment by isuran** [comment]
This field is always empty in my settings on phone. No help with or without decimal.

**Comment by pimpimmi** [comment]
Is this issue fixed?

**Comment by isuran** [comment]
I get error on watch, when writing to sqllite. Didn't have time yet to check yet

**Comment by pimpimmi** [comment]
I don't think this is relevant anymore. Please tell me if you find some other bugs.
