### ISSUE TITLE
When the sensor not correctly works, please add a error message

### ISSUE THREAD

**Issue by Matze1985** [pimpimmi/LibreAlarm#8]
I found an error, where the sensor is not properly seated on the skin. 
Good is here a error message, please check the sensor on the skin and not negative value.

![screenshot_20160702-202510](https://cloud.githubusercontent.com/assets/20039797/16545366/5e3a3eae-4129-11e6-99c2-d42481198de0.png)

BR Mathias

**Comment by pimpimmi** [comment]
Agreed, there should be no negative values. Best solution is probably to have <2.0 if below 2.0.

**Comment by Matze1985** [comment]
The values working very good!
I think to 0.0 is ok, but under (-) is wrong, the sensor was wrong of my arm.

Here possibly an error message: 
- Check the sensor on the skin

I make a retest with a sensor, if needed. 
I then write a new comment

**Comment by Matze1985** [comment]
The retest has the same problem with the (-) value.
- When the sensor not correct sitting on the arm, comes a minus value.
- It is the sensor.

**Comment by pimpimmi** [comment]
The minus value is due to the prediction algorithm in the app. The app predicts what the glucose value in reality is based on the values from the sensor the last 15 minutes. If it's falling fast the prediction might get below 0.
